CustomXperienceHubProject/urls.py
from django.urls import path, include
from django.contrib import admin

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cuenta/', include('cuenta.urls')),
    path('panel/', include('panel.urls', namespace='panel')),
]

cuenta/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from django.conf.urls import url
from . import views

urlpatterns = [
    #path('login/', views.usuario_login, name='login')
    path('', views.dashboard, name='dashboard'),
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('usuariologout/', auth_views.LogoutView.as_view(), name='usuariologout'),
    path('password_change/',auth_views.PasswordChangeView.as_view(),name='password_change'),
    path('password_change/done/',auth_views.PasswordChangeDoneView.as_view(),name='password_change_done'),
]

panel/urls.py
from django.urls import path
from . import views

app_name = 'panel'
urlpatterns = [
    # post views
    # path('', views.post_list, name='post_list'),
    path('', views.PostListView.as_view(), name='post_list'),
    path('<int:year>/<int:month>/<int:day>/<slug:post>/',
         views.post_detail,
         name='post_detail'),
    path('<int:post_id>/compartir/',
         views.post_share,
         name='post_share'),
]

cuenta/models.py
from django.db import models

# Create your models here.

panel/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse

class PublishedManager(models.Manager):
    def get_queryset(self):
        return super(PublishedManager,self).get_queryset().filter(status='publicado')

class Post(models.Model):
    STATUS_CHOICES = (
        ('borrador','Borrador'),
        ('publicado','Publicado'),
    )
    titulo = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250,
                            unique_for_date='publicar')
    autor = models.ForeignKey(User,
                              on_delete=models.CASCADE,
                              related_name='panel_posts')
    cuerpo = models.TextField()
    publicar = models.DateTimeField(default=timezone.now)
    creado = models.DateTimeField(auto_now_add=True)
    actualizado = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=10,
                              choices=STATUS_CHOICES,
                              default='draft')
    objetos = models.Manager()
    publicado = PublishedManager()

    class Meta:
        ordering = ('-publicar',)

    def __str__(self):
        return self.titulo

    def get_absolute_url(self):
        return reverse('panel:post_detail',
                           args=[self.publicar.year,
                             self.publicar.month,
                             self.publicar.day,
                             self.slug])

class Comentario(models.Model):
    post = models.ForeignKey(Post,
                             on_delete=models.CASCADE,
                             related_name='comentarios')
    nombre = models.CharField(max_length=80)
    email = models.EmailField()
    cuerpo = models.TextField()
    creado = models.DateTimeField(auto_now_add=True)
    actualizado = models.DateTimeField(auto_now=True)
    activo = models.BooleanField(default=True)

    class Meta:
        ordering = ('creado',)

    def __str__(self):
        return 'Comentado por {} en {}'.format(self.nombre, self.post)

cuenta/forms.py
from django import forms

class LoginFormulario(forms.Form):
    usuario = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)

panel/forms.py
from django import forms
from .models import Comentario

class EmailPostFormulario(forms.Form):
    nombre = forms.CharField(max_length=25)
    email = forms.EmailField()
    para = forms.EmailField()
    comentarios = forms.CharField(required=False,
                                  widget=forms.Textarea)

class ComentarioFormulario(forms.ModelForm):
    class Meta:
        model = Comentario
        fields = ('nombre','email','cuerpo')

cuenta/views.py
from django.http import HttpResponse
from django.shortcuts import render
from django.contrib.auth import authenticate,login
from django.contrib.auth.decorators import login_required
from .forms import LoginFormulario

def usuario_login(request):
    if request.method == 'POST':
        formulario = LoginFormulario(request.POST)
        if formulario.is_valid():
            cd = formulario.cleaned_data
            usuario = authenticate(request,
                                   username=cd['usuario'],
                                   password=cd['password'])
            if usuario is not None:
                if usuario.is_active:
                    login(request, usuario)
                    return HttpResponse('Autenticado '\
                                        'satisfactoriamente')
                else:
                    return HttpResponse('Cuenta desactivada')
            else:
                return HttpResponse('Login invalido')
    else:
        formulario = LoginFormulario()

    return render(request, 'cuenta/login.html', {'formulario':formulario})

@login_required
def dashboard(request):
    return render(request,
                  'cuenta/dashboard.html',
                  {'seccion': 'dashboard'})

panel/views.py
from django.shortcuts import render, get_object_or_404
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.views.generic import ListView
from django.core.mail import send_mail
from .models import Post, Comentario
from .forms import EmailPostFormulario, ComentarioFormulario

def post_list(request):
    object_list=Post.publicado.all()
    paginator = Paginator(object_list, 3)  # 3 posts in each page
    page = request.GET.get('page')
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)
    return render(request,
                  'panel/post/listar.html',
                  {'page': page,
                   'posts': posts})

def post_detail(request, year, month, day, post):
    post = get_object_or_404(Post, slug=post,
                                   status='publicado',
                                   publicar__year=year,
                                   publicar__month=month,
                                   publicar__day=day)

    comentarios = post.comentarios.filter(activo=True)
    nuevo_comentario = None

    if request.method == 'POST':
        comentario_formulario = ComentarioFormulario(data=request.POST)
        if comentario_formulario.is_valid():
            nuevo_comentario = comentario_formulario.save(commit=False)
            nuevo_comentario.post = post
            nuevo_comentario.save()
    else:
        comentario_formulario = ComentarioFormulario()
    return render(request,
                  'panel/post/detalle.html',
                  {'post': post,
                  'comentarios': comentarios,
                  'nuevo_comentario': nuevo_comentario,
                  'comentario_formulario':comentario_formulario})

class PostListView(ListView):
    queryset = Post.publicado.all()
    context_object_name = 'posts'
    paginate_by = 3
    template_name = 'panel/post/listar.html'

def post_share(request, post_id):
    post = get_object_or_404(Post, id=post_id, status='publicado')
    enviado = False

    if request.method == 'POST':
        formulario = EmailPostFormulario(request.POST)
        if formulario.is_valid():
            cd = formulario.cleaned_data
            post_url = request.build_absolute_uri(post.get_absolute_url())
            subject = '{} ({}) te recomienda leer "{}"'.format(cd['nombre'], cd['email'], post.titulo)
            message = 'Lea "{}" en los comentarios de {}\n\n{}\:{}'.format(post.titulo, post_url, cd['nombre'], cd['comentarios'])
            send_mail(subject, message, 'experiencia-cliente@entel.pe',[cd['para']])
            enviado = True
        else:
            formulario = EmailPostFormulario()
        return render(request, 'panel/post/compartir.html', {'post': post,
                                                        'formulario': formulario,
                                                        'enviado': enviado})
    else:
        formulario = EmailPostFormulario()
    return render(request, 'panel/post/compartir.html', {'post': post,
                                                         'formulario': formulario})

cuenta/templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
  <title>{% block title %}{% endblock %}</title>
  <link href="{% static 'css/panel.css' %}" rel="stylesheet">
</head>
<body>
  <div id="content">
    {% block content %}
    {% endblock %}
  </div>
  <div id="sidebar">
    <h2>CX Panel</h2>
      <p>Este es el panel informativo</p>
    {% if request.user.is_authenticated %}
    <ul class="menu">
      <li {% if section == "dashboard" %}class="selected"{% endif %}>
        <a href="{% url "dashboard" %}">Dashboard</a>
      </li>
    </ul>
    {% endif %}
    <span class="user">
      {% if request.user.is_authenticated %}
        Hola {{ request.user.first_name }},
        <a href="{% url "usuariologout" %}">Desloguear</a>
      {% else %}
        <a href="{% url "login" %}">Acceder</a>
      {% endif %}
    </span>
  </div>
</body>
</html>

cuenta/templates/cuenta/dashboard.html
{% extends "base.html" %}

{% block title %}Dashboard{% endblock %}

{% block content %}
    <h1>Dashboard</h1>
    <p>Bienvenido a nuestro dashboard.</p>
{% endblock %}

cuenta/templates/cuenta/login.html
{% extends "base.html" %}
{% block title %}Log in{% endblock %}
{% block content %}
    <h1>Log in</h1>
    <p>Bienvenido, use este formulario para acceder:</p>
    <form action="." method="post">
        {{ formulario.as_p }}
        {% csrf_token %}
        <p><input type="submit" value="Acceder"></p>
    </form>
{% endblock %}

panel/templates/pagination.html
<div class="pagination">
  <span class="step-links">
    {% if page.has_previous %}
      <a href="?page={{ page.previous_page_number }}">Anterior</a>
    {% endif %}
    <span class="current">
      Página {{ page.number }} de {{ page.paginator.num_pages }}.
    </span>
      {% if page.has_next %}
        <a href="?page={{ page.next_page_number }}">Siguiente</a>
      {% endif %}
  </span>
</div>

panel/templates/panel/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
  <title>{% block title %}{% endblock %}</title>
  <link href="{% static 'css/panel.css' %}" rel="stylesheet">
</head>
<body>
  <div id="content">
    {% block content %}
    {% endblock %}
  </div>
  <div id="sidebar">
    <h2>CX Panel</h2>
      <p>Este es el panel informativo</p>
  </div>
</body>
</html>

panel/templates/panel/post/compartir.html
{% extends 'panel/base.html' %}

{% block title %}Compartir un post{% endblock %}

{% block content %}
    {% if enviado %}
        <h1>E-mail satisfactoriamente enviado</h1>
        <p>
            "{{ post.titulo }}" fue satisfactoriamente enviado a {{ formulario.cleaned_data.para }}.
        </p>
    {% else %}
        <h1>Compartir "{{ post.titulo }}" por e-mail</h1>
        <form action="." method="post">
            {{ formulario.as_p }}
            {% csrf_token %}
            <input type="submit" value="Enviar e-mail">
        </form>
    {% endif %}
{% endblock %}

panel/templates/panel/post/detalle.html
{% extends 'panel/base.html' %}

{% block title %}{{ post.titulo }}{% endblock %}
{% block content %}
<h1>{{ post.titulo }}</h1>
<p class="date">
Publicado {{ post.publicar }} por {{ post.autor }}
</p>
{{ post.cuerpo|linebreaks }}
<p>
    <a href="{% url 'panel:post_share' post.id %}">
    Compartir este Post
    </a>
</p>
{% with comentarios.count as total_comentarios %}
    <h2>
    {{ total_comentarios }} Comentario{{ total_comentarios|pluralize }}
    </h2>
{% endwith %}

{% for comentario in comentarios %}
    <div class="comment">
        <p class="info">
            Comentario {{ forloop.counter }} by {{ comentario.nombre }}
            {{ comentario.creado }}
        </p>
        {{ comentario.cuerpo|linebreaks }}
    </div>
{% empty %}
    <p>No hay comentarios aun.</p>
{% endfor %}

{% if nuevo_comentario %}
    <h2>Tu comentario ha sido agregado.</h2>
{% else %}
    <h2>Agregar nuevo comentario</h2>
    <form action="." method="post">
        {{ comentario_formulario.as_p }}
        {% csrf_token %}
        <p><input type="submit" value="Agregar comentario"></p>
    </form>
{% endif %}
{% endblock %}

panel/templates/panel/post/listar.html
{% extends "panel/base.html" %}

{% block title %}Panel CX{% endblock %}

{% block content %}
  <h1>Panel CX</h1>
  {% for post in posts %}
    <h2>
      <a href="{{ post.get_absolute_url }}">
        {{ post.titulo }}
      </a>
    </h2>
    <p class="date">
      Publicado {{ post.publicar }} por {{ post.autor }}
    </p>
    {{ post.cuerpo|truncatewords:30|linebreaks }}
  {% endfor %}
  {% include "pagination.html" with page=page_obj %}
{% endblock %}